const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("wrath", {
  health: async () => (await fetch("http://127.0.0.1:18972/health").then((r) => r.json()).catch(() => ({ relay: false }))),
  toggle: async (on) => (await fetch("http://127.0.0.1:18972/relay/toggle", { method: "POST", body: JSON.stringify({ on }) }).then((r) => r.json()).catch(() => ({ relay: false }))),
  pickUA: () => ipcRenderer.invoke("pick-ua"),
  shieldCount: () => ipcRenderer.invoke("shield-count"),
  setGeo: (m) => ipcRenderer.invoke("set-geo", m),
  getGeo: () => ipcRenderer.invoke("get-geo"),
  torRescan: () => ipcRenderer.invoke("tor-rescan"),
  siteGet: (h) => ipcRenderer.invoke("site-get", h),
  siteSet: (h, k, v) => ipcRenderer.invoke("site-set", h, k, v),
  histGet: () => ipcRenderer.invoke("hist-get"),
  histClear: () => ipcRenderer.invoke("hist-clear"),
  shieldLog: () => ipcRenderer.invoke("shield-log"),
  onionGet: () => ipcRenderer.invoke("onion-get"),
  vaultCount: () => ipcRenderer.invoke("vault-count"),
  vaultRead: () => ipcRenderer.invoke("vault-read"),
  vaultExport: () => ipcRenderer.invoke("vault-export"),
  vaultWipe: () => ipcRenderer.invoke("vault-wipe"),
  onHist: (cb) => ipcRenderer.on("hist", (_, v) => cb(v)),
  onVault: (cb) => ipcRenderer.on("vault", (_, v) => cb(v)),
  onDl: (cb) => ipcRenderer.on("dl", (_, v) => cb(v)),
  onShield: (cb) => ipcRenderer.on("shield", (_, n) => cb(n)),
});
